[build]
default-target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
image = "hkubota/cross-custom:aarch64-unknown-linux-gnu"
pre-build = [
"dpkg --add-architecture  $CROSS_DEB_ARCH",
"apt-get update && apt-get -y install libsdl2-dev:$CROSS_DEB_ARCH libsdl2-gfx-dev:$CROSS_DEB_ARCH libsdl2-image-dev:$CROSS_DEB_ARCH libsdl2-mixer-dev:$CROSS_DEB_ARCH libsdl2-ttf-dev:$CROSS_DEB_ARCH"
]
